services:
  # 1. The ML Service
  - type: web
    name: estate-sense-ml
    env: docker
    dockerContext: ./ml_service   
    plan: free
    region: ohio

  # 2. The Backend
  - type: web
    name: estate-sense-backend
    env: docker
    dockerContext: ./backend      
    plan: free
    region: ohio
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: "5000"
      - key: PYTHON_API_URL
        value: "https://estate-sense-ml.onrender.com"